### PR TITLE
Fix - Coordinators unable to add transaction to support request

### PR DESCRIPTION
**Pull request by nsiwnf**
## Changelog
- Fixed alert to render on error
- Fixed issue with not saving when adding transaction

## Link to issue:  
#431 

## Steps for QA/Special Notes:
- N/A

## Relevant Screenshots: 
- super important for UI tasks!

## Are you ready for review?:

- [ ] Added relevant tests
- [ ] Linked PR to the issue
- [ ] Added notes for QA/special notes
- [ ] Added revelant screenshots

### CODE REVIEW

**Comment by misternu** [comment]
https://github.com/MidwestAccessCoalition/lockbox_rails/commit/8ad45cab21076ed7e54efefd5f655feb79636a47 adds a validation that a lockbox transaction must have a debit or credit balance_effect, lockbox_partner/support_requests_controller#update does not flash an error when updatesupportrequest fails and 500s anyway

**Comment by misternu** [comment]
UpdateSupportRequest should be updated to include that all lockbox transactions are debits, and support request controller should be updated to show errors and set the @path variable on failure, I can commit on this

**Comment by misternu** [comment]
Instead of changing update support request, I set balance_effect to debit by default, as the support request edit page isn't going to have balance effect in its ui. It also should now properly show errors on update instead of 500ing when trying to render edit

**Comment by nsiwnf** [comment]
@BintLopez @misternu  I'm good with merging this - still working on an end-to-end test which I can commit in a follow-up PR

**Pull request merged**
